/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterTSol from './Counter.t.sol/index.js';
export * as shipmentSol from './Shipment.sol/index.js';